name = "hex-sparse-poly-mathlib"
defaultTargets = ["HexSparsePolyMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexSparsePoly"
git = "https://github.com/leanprover/hex-sparse-poly.git"
rev = "736b5ee9fa124eac406c8e475b7da58dfb13b173"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "885da1bf79c1d5b446d28df13f0dff26de5b4831"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexSparsePolyMathlib"
globs = [
  "HexSparsePolyMathlib",
  "HexSparsePolyMathlib.Equiv",
]

[[lean_lib]]
name = "HexSparsePolyMathlibTests"
globs = ["HexSparsePolyMathlib.LintTests"]
