name = "hex-sparse-poly-mathlib"
defaultTargets = ["HexSparsePolyMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexSparsePoly"
git = "https://github.com/leanprover/hex-sparse-poly.git"
rev = "6b980b6ee9c296f872bde1cc34b2343459d05180"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "a9eb9de8c92b96f57660d02c468f9f8622066641"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexSparsePolyMathlib"
globs = [
  "HexSparsePolyMathlib",
  "HexSparsePolyMathlib.Equiv",
]

[[lean_lib]]
name = "HexSparsePolyMathlibTests"
globs = ["HexSparsePolyMathlib.LintTests"]
