name = "hex-sparse-poly-mathlib"
defaultTargets = ["HexSparsePolyMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "v0.7.0"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "v0.7.0"

[[require]]
name = "HexSparsePoly"
git = "https://github.com/leanprover/hex-sparse-poly.git"
rev = "v0.7.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "d870b9068518a0870842d15a0cd42637ec30b587"

[[lean_lib]]
name = "HexSparsePolyMathlib"
